vich_uploader:
  db_driver: orm

  mappings:
    user:
      uri_prefix: /assets/images/user
      upload_destination: "%kernel.project_dir%/public/assets/images/user"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    cv:
      uri_prefix: /assets/images/cv
      upload_destination: "%kernel.project_dir%/public/assets/images/cv"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
